# Site settings
name: Akhil Arularasu
title: Akhil Arularasu | Personal Site
description: My Website
url: https://akhil-arularasu.github.io/
baseurl: ''
email: helloakhil@gmail.com
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:helloakhil@gmail.com
  - title: instagram
    url: https://instagram.com/akhil_arularasu
  - title: github
    url: https://github.com/akhil-arularasu
  - title: linkedin
    url: https://www.linkedin.com/in/akhil-arularasu/
  - title: google scholar
    url: https://scholar.google.com/citations?user=hmYAtXMAAAAJ&hl=en

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
